
package wsinterface;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "powerFault", targetNamespace = "http://schemas.hu.fnt.nl/berichten/fault")
public class Fault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PowerFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Fault(String message, PowerFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Fault(String message, PowerFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: wsinterface.PowerFault
     */
    public PowerFault getFaultInfo() {
        return faultInfo;
    }

}
